set nu rnu is ls=2 hls ts=4 sw=4 et sts=4 ai bs=2 sc acd mouse=a encoding=utf-8
syn on
filetype plugin indent on
colo desert
inoremap {<CR> {<CR>}<Esc>O
inoremap jj <Esc>
nnoremap <F8> :w <bar> !g++ -std=c++17 % -o %:r -O2<CR>
nnoremap <F9> :w <bar> !g++ -std=c++17 % -o %:r -Wall -Wextra -Wconversion -Wshadow -Wfatal-errors -fsanitize=undefined,address -g -Dgenshin <CR>
nnoremap <F10> :!./%:r <CR>
ca Hash w !cpp -dD -P -fpreprocessed \| tr -d '[:space:]' \| md5sum \| cut -c-6
